### ISSUE TITLE
getting started with hello world

### ISSUE THREAD

**Issue by nemoo** [rholder/gradle-one-jar#10]
Hi!

This is not an issue but a very basic question about getting started with a hello world example.

I have created a scala Application in src/main/scala/example/Hi.scala with this content: 

``` scala
package example

object Hi extends App {
Console.println("Hello World: " + (args mkString ", "))
}
```

furthermore i added a build.gradle file to the root of the project: 

``` groovy
apply plugin: 'gradle-one-jar'
apply plugin: 'scala'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.rholder:gradle-one-jar:1.0.3'
    }
}

task awesomeFunJar(type: OneJar) {
    mainClass = 'example.Hi'
}
```

When i now run the command gradle awesomeFunJar i get the error: 

> Execution failed for task ':compileScala'.
> 'compileScala.scalaClasspath' must not be empty

What do i have to do to get my standalone HelloWorld Example to run?

Thanks!

**Comment by rholder** [comment]
Hi @nemoo,

Sorry for the incredibly late response on this, but here's a full sample `build.gradle` file that should be just what you were looking for:

``` groovy
apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'scala'

group = 'com.github.rholder'
version = '1.0.0-SNAPSHOT'

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.github.rholder:gradle-one-jar:1.0.3'
    }
}
apply plugin: 'gradle-one-jar'

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.scala-lang:scala-library:2.9.1'
}

task wrapper(type: Wrapper) {
    gradleVersion = '1.6'
}

task awesomeJar(type: OneJar) {
    mainClass = 'com.github.rholder.scala.HelloWorld'
}
```

Here's the sample `HelloWorld` file I put in `src/main/scala/HelloWorld.scala`:

``` scala
package com.github.rholder.scala {
    object HelloWorld {
        def main(args: Array[String]) {
            println("Hello, world!")
        }
    }   
}
```

And finally, you should be able to build a standalone jar artifact with:

``` shell
gradle clean awesomeJar
```

I hope that helps, and I'll make a note to add a section on the README.md or possibly the wiki.

**Comment by rholder** [comment]
Closing this, since it's been answered elsewhere: http://forums.gradle.org/gradle/topics/how_to_create_a_simple_scala_standalone_jar
