### ISSUE TITLE
Include OneJar's Guice support

### ISSUE THREAD

**Issue by ben-manes** [rholder/gradle-one-jar#11]
The OneJar classloader is not compatible with Google Guice or Spring. The [framework extension](http://one-jar.sourceforge.net/index.php?page=frameworks&file=frameworks) jars should be included for building those type of applications.

**Comment by rholder** [comment]
That seems like a nice addition for rounding out One-Jar support for Gradle. Thanks for the heads up.

**Comment by ben-manes** [comment]
Oh, I'm a little wrong. Its part of the distribution but needs a new manifest attribute. This seems to work,

``` groovy
task oneJar(type: OneJar, group: "Build") {
  mainClass = mainClassName
  manifest {
    attributes 'One-Jar-URL-Factory': 'com.simontuffs.onejar.JarClassLoader$OneJarURLFactory'
  }
}
```

**Comment by walec51** [comment]
@ben-manes thanks for the tip. this attribute is also required for JavaFX applications that use FXML, without it the GUI wont be able to load classpath resources referenced in the FXML file.
